#!/bin/bash

if [ $# -ne 1 ]; then
  echo Usage: $(basename $0) '<dir>'
  exit 1
fi

DIR="$1"

if ! [ -d "$DIR" ]; then
  echo Directory \""$DIR"\" does not exist.
  exit 1
fi

TESTFILE=$(ls "$DIR"/frame*.png 2> /dev/null | head -1)
if ! [ -f "$TESTFILE" ]; then
  echo No frames in \""$DIR\"".
  exit 1
fi
DIGITS=$(expr ${#TESTFILE} - ${#DIR} - 10)

ENCODERS=(ffmpeg avconv)

for enc in ${ENCODERS[*]}; do
  if hash $enc 2> /dev/null; then
    ENCODER=$enc
    break
  fi
done

if [ -z $ENCODER ]; then
  echo "No encoders found.  I need at least one of the following:" ${ENCODERS[*]} > /dev/stderr
  exit 1
fi

$ENCODER -framerate 60 -i "$DIR"/frame%0${DIGITS}d.png -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p "$DIR"/movie.mp4
