#!/bin/bash

if [ $# -ne 1 ]; then
  echo Usage: $(basename $0) '<dir>'
  exit 1
fi

DIR="$1"

ENCODERS=(ffmpeg avconv)

for enc in ${ENCODERS[*]}; do
  if hash $enc 2> /dev/null; then
    ENCODER=$enc
    break
  fi
done

if [ -z $ENCODER ]; then
  echo "No encoders found.  I need at least one of the following:" ${ENCODERS[*]} > /dev/stderr
  exit 1
fi

NAME=$(ls "$DIR"/frame*.png | head -1)
DIGITS=$(expr ${#NAME} - ${#DIR} - 10)

$ENCODER -framerate 60 -i "$DIR"/frame%0${DIGITS}d.png -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p "$DIR"/movie.mp4
